#!/bin/bash

# Returns the current directory as absolute path, independently from where it was called from
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# Build & Push Docker Image
docker build -t spiddy/project-initializer:0.0.1 ${DIR}
docker push spiddy/project-initializer:0.0.1
